"""The fallback regression test (02_ARCHITECTURE.md section 7.8): a generated HTTP-level pytest file.

When no native regression test can be validated, Rook writes `rook/tests/test_rook_<cx_id>.py`. It
replays the counterexample over HTTP against a running app (`ROOK_BASE_URL`) and asserts that the rule
holds. The Judge (the engine) decides, through `run_regression`, which the generated file calls.

Safety: the file comes from a fixed template. The counterexample and the model (which hold untrusted
values: app responses, captured ids, Bob-written rule text) are embedded only as JSON text inside
Python string literals made by `repr()`, one literal per JSON line. The only other value put into
the code is the cx_id, which must fullmatch `cx_\\d{3,6}`. After rendering, the source is parsed and
its syntax tree must equal the template's (only the data strings may differ) and the data must
decode back to exactly what was embedded; otherwise nothing is written.

`run_generated_test` runs such a file (and only such a file) with pytest in a fresh temp dir, with a
minimal env and no conftest/ini/plugins picked up from the target repo.
"""

import ast
import asyncio
import json
import os
import re
import shutil
import signal
import subprocess
import sys
import tempfile
from collections.abc import Callable, Mapping
from pathlib import Path
from typing import Any

from rook.engine.executor import Executor
from rook.export.counterexample import (
    CX_ID,
    Counterexample,
    CxReplay,
    replay_counterexample,
    rule_only_model,
    write_new_file,
)
from rook.model.schema import RookModel
from rook.model.template import placeholders
from rook.sandbox.base import ExecResult

TEST_DIR = Path("rook") / "tests"
FORMAT = 1
ENV_PREFIX = "ROOK_ENV_"  # env values the model needs reach the test as ROOK_ENV_<NAME>
BASE_URL_ENV = "ROOK_BASE_URL"
STRICT_ENV = "ROOK_REGRESSION_STRICT"  # "1": a missing base URL or rook install fails instead of skips
DEFAULT_TIMEOUT = 300.0
_ENV_NAME = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")
_SYSTEM_PATH = ("/usr/local/bin", "/usr/bin", "/bin")

_TEMPLATE = """\
# Generated by Rook: the regression test for counterexample __CX_ID__. Do not edit.
#
# It replays the counterexample's exact steps over HTTP against a running app and asserts that the
# rule holds. Run it with:  ROOK_BASE_URL=http://127.0.0.1:8000 pytest __FILE__
# Values the model reads from env are taken from ROOK_ENV_<NAME>. Without ROOK_BASE_URL the test is
# skipped (ROOK_REGRESSION_STRICT=1 makes that a failure). COUNTEREXAMPLE is plain JSON data.
import json
import os

import pytest

COUNTEREXAMPLE = json.loads(
    "\\n".join(
        [
__DATA__
        ]
    )
)


def test_rook___CX_ID__() -> None:
    strict = os.environ.get("ROOK_REGRESSION_STRICT") == "1"
    base_url = os.environ.get("ROOK_BASE_URL", "")
    if not base_url:
        if strict:
            pytest.fail("ROOK_BASE_URL is not set")
        pytest.skip("set ROOK_BASE_URL to the running app's base URL")
    try:
        from rook.export.tests import run_regression
    except ImportError:
        if strict:
            raise
        pytest.skip("rook is not installed (pip install rook-cli)")
    outcome = run_regression(COUNTEREXAMPLE, base_url, os.environ)
    assert outcome.holds, outcome.message
"""


class UnsafeTestError(ValueError):
    """The rendered test did not have exactly the template's shape (never written or run)."""


def fallback_test_name(cx_id: str) -> str:
    if not CX_ID.fullmatch(cx_id):
        raise ValueError(f"invalid cx_id {cx_id!r}")
    return f"test_rook_{cx_id}.py"


def payload(cx: Counterexample, model: RookModel) -> dict[str, Any]:
    """What the generated test embeds: the counterexample and the model with only its rule."""
    return {
        "format": FORMAT,
        "counterexample": cx.model_dump(mode="json"),
        "model": rule_only_model(model, cx).model_dump(mode="json", by_alias=True, exclude_none=True),
    }


def _data_json(data: Mapping[str, Any]) -> str:
    # ensure_ascii + JSON escaping: no raw newline or control char can reach a line of this text.
    return json.dumps(data, indent=2, sort_keys=True, ensure_ascii=True, allow_nan=False)


def _render(cx_id: str, lines: list[str]) -> str:
    name = fallback_test_name(cx_id)
    data = "\n".join(f"            {line!r}," for line in lines)
    source = _TEMPLATE.replace("__FILE__", name).replace("__CX_ID__", cx_id)
    return source.replace("__DATA__\n", data + "\n" if data else "")


def _data_list(tree: ast.Module) -> ast.List:
    for node in tree.body:
        if isinstance(node, ast.Assign) and [ast.unparse(t) for t in node.targets] == ["COUNTEREXAMPLE"]:
            call = node.value
            if isinstance(call, ast.Call) and call.args and isinstance(call.args[0], ast.Call):
                inner = call.args[0]
                if inner.args and isinstance(inner.args[0], ast.List):
                    return inner.args[0]
    raise UnsafeTestError("COUNTEREXAMPLE data list not found")


def _shape(tree: ast.Module) -> str:
    _data_list(tree).elts = []
    return ast.dump(tree, include_attributes=False)


def check_generated(source: str, cx_id: str, data_json: str | None = None) -> str:
    """Raise UnsafeTestError unless `source` is the template with only string data embedded (and,
    if given, exactly `data_json`). Returns the embedded JSON text."""
    try:
        tree = ast.parse(source)
        reference = ast.parse(_render(cx_id, []))
    except SyntaxError as exc:
        raise UnsafeTestError(f"generated test does not parse: {exc}") from exc
    lines: list[str] = []
    for e in _data_list(tree).elts:
        if not (isinstance(e, ast.Constant) and isinstance(e.value, str)):
            raise UnsafeTestError("generated test data holds something other than string literals")
        lines.append(e.value)
    embedded = "\n".join(lines)
    if data_json is not None and embedded != data_json:
        raise UnsafeTestError("generated test data does not match the counterexample")
    if _shape(tree) != _shape(reference):
        raise UnsafeTestError("generated test code differs from the template")
    return embedded


def render_fallback_test(cx: Counterexample, model: RookModel) -> str:
    data_json = _data_json(payload(cx, model))
    source = _render(cx.cx_id, data_json.splitlines())
    check_generated(source, cx.cx_id, data_json)
    return source


def prompt_view(source: str, cx_id: str, mask: Callable[[Any], Any] | None = None) -> str:
    """The generated test as an agent is shown it: the same file, with the run-specific values of the
    embedded counterexample replaced by fixed labels (`created_at` -> `<time>`, the random search `seed`
    -> `<seed>`) and `mask` applied to `observed`, so the prompt (a recording key) is the same on every
    run. The file on disk, which the engine runs, is unchanged. Anything that is not a generated test for
    `cx_id` is returned as it is."""
    try:
        data = json.loads(check_generated(source, cx_id))
    except (UnsafeTestError, ValueError):
        return source
    cx = data.get("counterexample") if isinstance(data, dict) else None
    if not isinstance(cx, dict):
        return source
    cx["created_at"] = "<time>"
    cx["seed"] = "<seed>"
    if mask is not None and "observed" in cx:
        cx["observed"] = mask(cx["observed"])
    return _render(cx_id, _data_json(data).splitlines())


def write_fallback_test(root: Path, cx: Counterexample, model: RookModel) -> Path:
    """Write `root/rook/tests/test_rook_<cx_id>.py` (never overwriting) and return its path."""
    source = render_fallback_test(cx, model)
    return write_new_file(root, TEST_DIR, fallback_test_name(cx.cx_id), source)


# --- the runtime side, called by the generated test ---


def env_names(model: RookModel) -> list[str]:
    """The `{{env.NAME}}` names the model's requests use."""
    names = placeholders(model.model_dump(mode="json", by_alias=True, exclude_none=True))
    return sorted({n.split(".")[1] for n in names if n.startswith("env.")})


def run_regression(data: Mapping[str, Any], base_url: str, environ: Mapping[str, str]) -> CxReplay:
    """Replay the embedded counterexample once against `base_url`; the Judge decides."""
    if data.get("format") != FORMAT:
        raise ValueError(f"unsupported regression data format {data.get('format')!r}")
    model = RookModel.model_validate(data["model"])
    cx = Counterexample.model_validate(data["counterexample"])
    names = env_names(model)
    missing = [ENV_PREFIX + n for n in names if ENV_PREFIX + n not in environ]
    if missing:
        return CxReplay(None, 0, [f"missing env: {', '.join(missing)}"])
    env = {n: environ[ENV_PREFIX + n] for n in names}

    async def replay() -> CxReplay:
        async with Executor(model, base_url, env=env) as ex:
            return await replay_counterexample(ex, model, cx)

    return asyncio.run(replay())


# --- running a generated test file ---


def _kill_group(pgid: int) -> None:
    try:
        os.killpg(pgid, signal.SIGKILL)
    except ProcessLookupError:
        pass


def run_generated_test(
    test_file: Path, base_url: str, env: Mapping[str, str] | None = None, *, timeout: float = DEFAULT_TIMEOUT
) -> ExecResult:
    """Run a generated fallback test with pytest in a fresh temp dir and return its exit code.

    The file is checked against the template first, then copied alone into the temp dir, which gets
    an empty pytest.ini: no conftest.py, ini, plugin or cache from the target repo is loaded. The
    child env is built from scratch (none of Rook's env): PATH, the base URL, strict mode and
    `ROOK_ENV_<NAME>` for each value in `env`.
    """
    source = test_file.read_text(encoding="utf-8")
    match = re.fullmatch(r"test_rook_(cx_\d{3,6})\.py", test_file.name)
    if match is None:
        raise UnsafeTestError(f"{test_file.name} is not a generated Rook test")
    check_generated(source, match.group(1))

    child_env = {
        "PATH": os.pathsep.join(dict.fromkeys((str(Path(sys.executable).parent), *_SYSTEM_PATH))),
        "LANG": "C.UTF-8",
        "PYTHONDONTWRITEBYTECODE": "1",
        "PYTEST_DISABLE_PLUGIN_AUTOLOAD": "1",
        BASE_URL_ENV: base_url,
        STRICT_ENV: "1",
    }
    for name, value in (env or {}).items():
        if not _ENV_NAME.fullmatch(name) or "\x00" in value:
            raise ValueError(f"invalid env name or value for {name!r}")
        child_env[ENV_PREFIX + name] = value

    tmp = Path(tempfile.mkdtemp(prefix="rook-regression-"))
    try:
        child_env["HOME"] = child_env["TMPDIR"] = str(tmp)
        target = tmp / test_file.name
        target.write_text(source, encoding="utf-8")
        ini = tmp / "pytest.ini"
        ini.write_text("[pytest]\n", encoding="utf-8")
        argv = [
            sys.executable, "-m", "pytest", "-q", "-p", "no:cacheprovider", "--noconftest",
            "-c", str(ini), "--rootdir", str(tmp), str(target),
        ]  # fmt: skip
        proc = subprocess.Popen(
            argv,
            cwd=tmp,
            env=child_env,
            stdin=subprocess.DEVNULL,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            start_new_session=True,
            close_fds=True,
        )
        try:
            out, err = proc.communicate(timeout=timeout)
        except subprocess.TimeoutExpired:
            _kill_group(proc.pid)
            out, err = proc.communicate()
            return ExecResult(-1, out.decode(errors="replace"), f"timeout after {timeout:g}s")
        finally:
            _kill_group(proc.pid)
        return ExecResult(proc.returncode, out.decode(errors="replace"), err.decode(errors="replace"))
    finally:
        shutil.rmtree(tmp, ignore_errors=True)
