"""Label-based cleanup of Docker sandbox resources, and the watchdog that runs it if Rook dies.

Every container, network, volume and image a DockerSandbox creates carries the label `rook.run=<name>`.
`sweep(name)` removes all of them. `atexit` and signal handlers cover normal exits, exceptions and
SIGTERM/SIGHUP, but nothing in-process survives SIGKILL or an OOM kill. So each sandbox also starts this
module as a small watchdog in its own session:

    python -m rook.sandbox.reaper <name>

It blocks reading its stdin, a pipe whose write end only the Rook process holds. When that process exits,
however it dies, the pipe closes, the read returns EOF and the watchdog sweeps the label.

This module has no Rook imports so the watchdog starts fast.
"""

import os
import re
import subprocess
import sys
from collections.abc import Mapping, Sequence

RUN_LABEL = "rook.run"
SANDBOX_LABEL = "rook.sandbox"
OWNER_LABEL = "rook.owner_pid"
# Sandbox names are generated by DockerSandbox; the check stops a bad name reaching a docker filter.
_NAME = re.compile(r"rook-[a-z0-9][a-z0-9_.-]{0,62}")
_SWEEP_TIMEOUT = 120.0
# The docker CLI only needs these; nothing else from Rook's env (API keys, tokens) is passed on.
_CLI_ENV_NAMES = (
    "PATH",
    "HOME",
    "LANG",
    "XDG_RUNTIME_DIR",
    "DOCKER_HOST",
    "DOCKER_CONTEXT",
    "DOCKER_CONFIG",
    "DOCKER_CERT_PATH",
    "DOCKER_TLS_VERIFY",
)


def check_name(name: str) -> str:
    if not _NAME.fullmatch(name):
        raise ValueError(f"not a sandbox name: {name!r}")
    return name


def cli_env(environ: Mapping[str, str] | None = None) -> dict[str, str]:
    """The env for `docker` CLI calls: only what the CLI needs to find the daemon and its config.

    This also matters for compose, which interpolates `${VAR}` from this env into the compose file.
    """
    source = os.environ if environ is None else environ
    env = {name: source[name] for name in _CLI_ENV_NAMES if name in source}
    env.setdefault("PATH", "/usr/local/bin:/usr/bin:/bin")
    env["DOCKER_CLI_HINTS"] = "false"
    return env


def docker(args: Sequence[str], *, timeout: float = _SWEEP_TIMEOUT) -> subprocess.CompletedProcess[str]:
    """Run `docker <args>` (argv, no shell, stdin closed). Never raises for a non-zero exit."""
    try:
        return subprocess.run(
            ["docker", *args],
            env=cli_env(),
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            timeout=timeout,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired) as exc:
        return subprocess.CompletedProcess(["docker", *args], 125, "", str(exc))


def _ids(kind: str, label: str) -> list[str]:
    cmd = {
        "container": ["ps", "-aq"],
        "network": ["network", "ls", "-q"],
        "volume": ["volume", "ls", "-q"],
        "image": ["image", "ls", "-q"],
    }[kind]
    out = docker([*cmd, "--filter", f"label={label}"]).stdout
    return sorted(set(out.split()))


def sweep(name: str) -> None:
    """Force-remove every container, network, volume and image labelled `rook.run=<name>`."""
    label = f"{RUN_LABEL}={check_name(name)}"
    containers = _ids("container", label)
    if containers:
        docker(["rm", "-f", "-v", *containers])
    for kind, rm in (
        ("network", ["network", "rm"]),
        ("volume", ["volume", "rm", "-f"]),
        ("image", ["image", "rm", "-f"]),
    ):
        ids = _ids(kind, label)
        if ids:
            docker([*rm, *ids])


def sweep_stale() -> list[str]:
    """Sweep sandboxes whose owning Rook process is gone (a crash the watchdog could not handle)."""
    out = docker(
        [
            "ps",
            "-a",
            "--filter",
            f"label={SANDBOX_LABEL}",
            "--format",
            f'{{{{.Label "{RUN_LABEL}"}}}} {{{{.Label "{OWNER_LABEL}"}}}}',
        ]
    ).stdout
    swept = []
    for line in out.splitlines():
        name, _, pid = line.strip().partition(" ")
        if not _NAME.fullmatch(name) or not pid.isdigit() or _alive(int(pid)):
            continue
        sweep(name)
        swept.append(name)
    return swept


def _alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


def main(argv: Sequence[str]) -> int:
    if len(argv) != 1:
        print("usage: python -m rook.sandbox.reaper <sandbox-name>", file=sys.stderr)
        return 2
    name = check_name(argv[0])
    try:
        while sys.stdin.buffer.read(4096):  # anything written is ignored; only EOF matters
            pass
    except (OSError, KeyboardInterrupt):
        pass
    sweep(name)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
