"""One valid sample payload per event type, for the TUI tests (and later 026/027 widget tests)."""

from typing import Any

SAMPLES: dict[str, dict[str, Any]] = {
    "run.created": {
        "repo": {"kind": "demo", "ref": "main", "name": "shop-app"},
        "request": "find bugs in my app",
        "options": {"auto": False, "budget": 1.5},
    },
    "run.phase": {"phase": "SEARCH"},
    "agent.started": {"agent": "scout", "call_id": "c1", "detail": "reading repo"},
    "agent.progress": {"agent": "scout", "call_id": "c1", "detail": "found 7 endpoints"},
    "agent.finished": {"agent": "scout", "call_id": "c1", "ok": True, "summary": "Node.js · Express",
                       "cost": 0.02, "recorded": True},
    "engine.started": {"worker": "runner", "label": "searching"},
    "engine.progress": {"worker": "runner", "pct": 42.5, "label": "searching", "count": 1200},
    "engine.finished": {"worker": "runner", "ok": False, "summary": "Rule broken · refunds ≤ paid"},
    "question.asked": {"question_id": "q1", "kind": "approve_rules", "text": "Approve these 4 rules?",
                       "options": [{"id": "yes", "label": "Yes"}, {"id": "no", "label": "No"}]},
    "question.answered": {"question_id": "q1", "answer": "yes", "by": "user"},
    "repo.summary": {"language": "Node.js", "framework": "Express", "entrypoints": ["src/app.js"],
                     "routes_files": ["src/routes.js"], "models_files": [], "test_command": "npm test",
                     "business_summary": "a small shop [with refunds]"},
    "sandbox.ready": {"base_url_redacted": "http://127.0.0.1:****", "mode": "docker"},
    "model.actions": {"actors": [], "actions": [{"name": "buy"}, {"id": "refund"}], "state": []},
    "rules.proposed": {"rules": [{"id": "r1", "text": "Refunds never exceed amount paid"}]},
    "rules.reviewed": {"verdicts": [{"rule_id": "r1", "ok": True}]},
    "rules.approved": {"rule_ids": ["r1"]},
    "search.progress": {"sequences": 2140, "per_sec": 1140.0, "rules": {"r1": "holding"}},
    "violation.found": {"violation_id": "v1", "rule_id": "r1", "steps_count": 12, "observed": {"refunded": 110}},
    "shrink.step": {"violation_id": "v1", "steps_count": 3},
    "counterexample.saved": {"cx_id": "cx_001", "rule_id": "r1", "rule_text": "Refunds never exceed amount paid",
                             "steps": ["buy(100)", "refund(60)", "refund(50)"], "observed": 110, "expected": 100,
                             "reproduced": "10/10", "flaky": False, "test_path": None},
    "diagnosis.ready": {"cx_id": "cx_001", "file": "src/refunds.js", "line": 42,
                        "explanation": "each refund is checked alone", "reviewed": True},
    "fix.ready": {"cx_id": "cx_001", "files": ["src/refunds.js"], "diff": "-a\n+b\n", "reviewed": True},
    "verify.step": {"cx_id": "cx_001", "check": "replay", "status": "passed", "detail": "second refund rejected"},
    "verify.done": {"cx_id": "cx_001", "verified": True, "summary": "all checks passed"},
    "pr.opened": {"url": "https://github.com/acme/shop/pull/88", "number": 88, "branch": "rook/cx_001"},
    "chat.message": {"role": "guide", "text": "2,140 sequences so far."},
    "cost.update": {"coins_total": 0.46},
    "log": {"level": "warn", "text": "slow health check"},
    "run.finished": {"status": "done", "summary": "1 fix verified"},
}
